In [3]:
import numpy as np

In [5]:
# number of words (n) == 2
# number of dimensions (d) == 4
Q = np.array([[2, 3, 4, 5],
              [9, 1, 2, 6]])

K = np.array([[3, 7, 1, 1],
              [2, 8, 2, 3]])

[(Q1,K1), (Q1, K2], = How to combine all the keys according to the first query

 [(Q2,K1) (Q2, K2)] = How to combine all the keys according to the second query

In [6]:
np.dot(Q, K.T)

array([[36, 51],
       [42, 48]])

If you were to do it the other way (**which wouldn't make any sense), it would look like this.  Every row would then show How to combine all the queries according to the key.

[(K1, Q1), (K1, Q2)] = How to combine the queries according to the first Key

[(K2, Q1), (K2, Q2)] = How to combine the queries according to the second Key

In [20]:
np.dot(K, Q.T)

array([[36, 42],
       [51, 48]])

### What about if both matrices were transposed to begin with?  

A: The result would mean something completely different. Q * K.T  != Q.T * K

In [21]:
Q.T.dot(K)

array([[24, 86, 20, 29],
       [11, 29,  5,  6],
       [16, 44,  8, 10],
       [27, 83, 17, 23]])

In [22]:
np.dot(Q, K.T)

array([[36, 51],
       [42, 48]])